INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('rc1', parsedatetime('01 APR 2018', 'dd MMM yyyy'), '40000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc1'),0);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc1'),1);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd1', parsedatetime('01 APR 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd1'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd1'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('hb1', parsedatetime('03 APR 2018', 'dd MMM yyyy'), '-16822');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb1'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb1'),4);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd2', parsedatetime('08 APR 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd2'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd2'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd3', parsedatetime('15 APR 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd3'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd3'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd4', parsedatetime('22 APR 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd4'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd4'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd5', parsedatetime('29 APR 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd5'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd5'),3);

INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('rc2', parsedatetime('01 MAY 2018', 'dd MMM yyyy'), '40000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc2'),0);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc2'),1);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('hb3', parsedatetime('01 MAY 2018', 'dd MMM yyyy'), '-16822');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb3'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb3'),4);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd6', parsedatetime('06 MAY 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd6'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd6'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd7', parsedatetime('13 MAY 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd7'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd7'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd8', parsedatetime('20 MAY 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd8'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd8'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd9', parsedatetime('27 MAY 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd9'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd9'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('hb5', parsedatetime('29 MAY 2018', 'dd MMM yyyy'), '-16822');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb5'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb5'),4);

INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('rc3', parsedatetime('01 JUN 2018', 'dd MMM yyyy'), '40000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc3'),0);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc3'),1);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd10', parsedatetime('03 JUN 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd10'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd10'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd11', parsedatetime('10 JUN 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd11'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd11'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd12', parsedatetime('17 JUN 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd12'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd12'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd13', parsedatetime('24 JUN 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd13'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd13'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('hb7', parsedatetime('26 JUN 2018', 'dd MMM yyyy'), '-16822');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb7'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb7'),4);

INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('rc4', parsedatetime('01 JUL 2018', 'dd MMM yyyy'), '40000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc4'),0);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='rc4'),1);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd14', parsedatetime('01 JUL 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd14'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd14'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd15', parsedatetime('08 JUL 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd15'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd15'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd16', parsedatetime('15 JUL 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd16'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd16'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd17', parsedatetime('22 JUL 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd17'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd17'),3);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('hb9', parsedatetime('24 JUL 2018', 'dd MMM yyyy'), '-16822');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb9'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='hb9'),4);
INSERT INTO ms_transaction (transaction_id, date, pence) VALUES ('dd18', parsedatetime('29 JUL 2018', 'dd MMM yyyy'), '-5000');
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd18'),2);
INSERT INTO ms_transaction_tags(transaction_id, tags) VALUES ((SELECT transaction_id from ms_transaction WHERE transaction_id='dd18'),3);